name: HealthData
description: 'Example of a harvested site creaed with Interra Catalog'
prodUrl: http://healthdata-example.interra.io
testUrl: http://localhost:3000
devUrl: http://localhost:3000
identifier: healthdata
schema: pod-full
front-page-icon-collection: theme
front-page-icons:
 - health
 - medicare
 - facilities-and-services
 - hospital-compare
 - diseases-and-conditions 
 - demographics
search:
  type: elasticSearch
  endpoint: https://aj1585l13a.execute-api.us-west-2.amazonaws.com/prod 
  fields:
    - title
    - keyword
    - publisher
    - description
    - theme
    - modified
    - distribution
private:
  algolia:
    applicationId: 
    apiKey:  
    index: healthdata 
  aws:
fontConfig:
  backColor: "#fff"
  link: "#0A77BD"
  linkHover: "#002245"
  linkFocus: "#002245"
  navBarBackColor: "#0A77BD"
  navBarLink: "#FFF"
  navBarLinkHover: "#FFF"
  navBarLinkHoverBack: "#002245"
  navBarLinkActive: "#FFF"
  navBarLinkActiveBack: "#005489"
  navBarLinkActiveHoverBack: "#005489"
  navBarLinkActiveHover: "#FFF"
#  heroImageUrl:
  heroBackColor: "#003366"
  heroSearchIconBackColor: "#0A77BD"
  heroSearchIconBorderColor: "#999"
#  heroSearchOutlineColor: "#222"
#  heroSearchOutlineBorderColor:
  footerBackColor: "#319bbf"
  footerFontColor: "#caeef9"
  footerLinkColor: "#FFFFFF"
